### ISSUE TITLE
interop with mainstream grpc

### ISSUE THREAD

**Issue by mediabuff** [cyanfish/grpc-dotnet-namedpipes#11]
https://github.com/cyanfish/grpc-dotnet-namedpipes/issues/2#issuecomment-623641755

Could you please elaborate what makes this "not interoperable" ?

**Comment by cyanfish** [comment]
Well, first of all, named pipe-based gRPC inherently won't interoperate with socket-based gRPC (which is almost all the implementations to date).

But the point of that comment is that:
- [grpc-go](https://github.com/grpc/grpc-go) supports named pipes
- There are long-term goals to implement named pipe support in [grpc-dotnet](https://github.com/grpc/grpc-dotnet) and others
- But this project won't ever interoperate with those, because they use the (heavyweight, hard-to-implement, but more standardized) approach of running HTTP/2 over named pipes, while this project uses a simple [custom protocol](https://github.com/cyanfish/grpc-dotnet-namedpipes/blob/750c652386012bc512be934244ffafbfc8fa632a/GrpcDotNetNamedPipes/Internal/transport.proto#L23) instead.

So applications using grpc-dotnet-namedpipes (this project) will only ever be able to communicate with other applications using grpc-dotnet-namedpipes, unless someone goes to the effort of cloning the protocol.

**Comment by mediabuff** [comment]
thanks for the prompt response. Did'nt realize grpc was hardwired to http/2. Can't interoperability occur at a layer above at the framing level - the frames can be protocol agnostic ?

**Comment by cyanfish** [comment]
Yeah, it's tied too closely to http2, making use of its bidirectional streaming support among other things. [These slides](https://www.slideshare.net/VarunTalwar4/grpc-design-and-implementation) might be of some interest.

**Comment by mediabuff** [comment]
thank you!!
