### ISSUE TITLE
Are you planing on putting this on grpc/grpc-dotnet?

### ISSUE THREAD

**Issue by taori** [cyanfish/grpc-dotnet-namedpipes#2]
This package is pretty cool. I just needed some IPC and figured i'll do some research and ran into this. This seems like a great typed alternative.

**Comment by cyanfish** [comment]
Because of the way it's implemented, this package will never be interoperable with any other gRPC named pipe implementation, so it's unlikely to be officially endorsed (I talked about this a bit with jtattermusch).

The long term story for gRPC named pipes is to use HTTP over named pipes. That should [eventually](https://github.com/dotnet/runtime/issues/28721) be supported in ASP.NET Core, which will let it be implemented in grpc-dotnet.

In the meantime this package should work fine if you don't need that interoperability.

**Comment by taori** [comment]
What a pitty. I particularly like that it does not bind to ports and works the way it does. Thanks for your work in that case! :)
